[package]
name = "hands_tracking_workshop"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
    "crates/*"
]

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[dependencies]
bevy = { version = "0.13.0", features = ["dynamic_linking"] }
bevy-inspector-egui = "0.23.3"
