[package]
name = "leap_input"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.13.2", features = ["dynamic_linking"] }
leaprs = { version = "0.2.1", features = ["glam"] }
ringbuf = "0.3.3"
